routes/web.php
<?php
/*
 * Rotas para a área restrita
 */
Route::namespace('Admin')->group(function() {
    /*
     * As rotas definidas abaixo pertencem a area restrita
     * e são executadas atravez do middleware de autenticação
     * Se o usuário não estiver autenticado na ferramenta, ele será redirecoinado para a tela de login 
     */
    Route::group(['middleware' => 'auth'], function() {

        /*
         * Rotas para o modulo de Status
         */
        Route::get('/admin/statuses', 'StatusController@index');
        Route::match(['get', 'post'], '/admin/status/create', 'StatusController@create');
        Route::match(['get', 'post'], '/admin/status/update/{id}', 'StatusController@update');
        Route::get('/admin/status/delete/{id}', 'StatusController@delete');
        Route::get('/admin/status/{id}', 'StatusController@show');

        /*
         * Rotas para o modulo de maquinas 
         */
        Route::get('/admin/engines', 'EngineController@index');
        Route::match(['get', 'post'], '/admin/engine/create', 'EngineController@create');
        Route::match(['get', 'post'], '/admin/engine/update/{id}', 'EngineController@update');
        Route::get('/admin/engine/delete/{id}', 'EngineController@delete');
        Route::get('/admin/engine/{id}', 'EngineController@show');

        /*
         * Rotas para o simulador de eventos 
         */
        Route::get('/admin/simulator', 'SimulatorController@index');
        Route::match(['get', 'post'], '/admin/simulator/create', 'SimulatorController@create');
        Route::match(['get', 'post'], '/admin/simulator/update/{id}', 'SimulatorController@update');
        Route::get('/admin/simulator/delete/{id}', 'SimulatorController@delete');
        Route::get('/admin/simulator/update-engine/{id}', 'SimulatorController@updateEngine');
    });
});

/*
 * Rotas de autenticação
 */
Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/login', 'Auth\LoginController@login');
Route::get('/logout', 'Auth\LoginController@logout')->name('logout');

app/Models/Custom/BDSModel.php
<?php

namespace App\Models\Custom;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Validator as FacadeValidator;
use Illuminate\Validation\Validator;

/**
 * This class implements validations methods used by it called class
 *
 * The called class must implement a public customRules method, 
 * which must return a key pair array used by Illuminate\Support\Facades\Validator
 * Check Laravel documentation page for facade validator
 *
 * To create custom validation rules, your model must contain a method customRules,
 * which will return a key pair array values. 
 * Its key should be the property to be validated.
 * Its value should be an array, with method names inside its class
 *
 * Sample return for customRules method: 
 * 
 * [
 *   'field1' => ['validationMethod1', 'validationMethod2'],
 *   'field2' => ['validationMethod2']
 * ]
 * 
 * - In this sample, 'validationMethod1' and 'validationMethod2' must be declared on its called class 
 * and should return an string with the error, or an empty string
 *
 * @author Bruno Vieira <vrunobieira@gmail.com>
 */
abstract class BDSModel extends Model
{

    /**
     * Validator object
     * 
     * @var \Illuminate\Validation\Validator
     */
    private $validator = null;

    /**
     * Checks whether the validator was called previously by the model
     * 
     * @var boolean
     */
    private $didValidatorRun = false;

    /**
     * Call parent constructor an dispatch validator events
     * 
     * @param array $attributes 
     */
    public function __construct(array $attributes = [])
    {
        // run parent constructor
        parent::__construct($attributes);

        // register the validator within the class
        $this->_registerValidator();
    }

    /**
     * Accessor for getErrorMessages()
     * 
     * @return array
     */
    public function getErrorMessagesAttribute() : array
    {
        return $this->getErrorMessages();
    }

    /**
     * Accessor for hasErrors()
     * 
     * @return bool
     */
    public function getHasErrorsAttribute() : bool
    {
        return $this->hasErrors();
    }

    /**
     * Run model validations
     *
     * @return bool
     */
    public function validate() : bool
    {
        // register the validator within the class
        $this->_registerValidator();

        // change flag to inform the validator has run by public call
        $this->_setDidValidate();

        // returns true if does not contain errors
        return !$this->hasErrors();
    }

    /**
     * Checks whether the validation has run and the model has errors
     * 
     * @var boolean
     */
    public function hasErrors() : bool
    {
        return $this->_getDidValidatorRun()
            ? $this->_getValidator()->fails()
            : false;
    }

    /**
     * Retrieves error messages list
     * 
     * @return array
     */
    public function getErrorMessages() : array
    {
        return $this->hasErrors()
            ? $this->_getValidator()->errors()->all()
            : [];
    }

    /**
     * Setter for BDSModel::$validator
     * 
     * @param Illuminate\Validation\Validator $validator 
     * @return void
     */
    private function _setValidator(Validator $validator)
    {
        $this->validator = $validator;
    }

    /**
     * Getter for BDSModel::$validator
     * 
     * @return Illuminate\Validation\Validator
     */
    private function _getValidator() : Validator
    {
        return $this->validator;
    }

    /**
     * Start new validator and binds it to this class
     * 
     * @return void
     */
    private function _initValidator()
    {
        $validator = FacadeValidator::make($this->getAttributes(), $this->rules());

        $this->_setValidator($validator);
    }

    /**
     * Getter for $validator
     * 
     * @return Illuminate\Validation\Validator
     */
    protected function getValidator() : Validator
    {
        return $this->validator;
    }

    /**
     * Run additional validations registered by called class
     * 
     * @return void
     */
    private function _registerCustomRules()
    {
        // checks whether the customRules method is declared on called class
        // otherwise bypass register event
        if (!method_exists(get_called_class(), 'customRules')) 
            return;

        // get validator object
        $validator = $this->_getValidator();

        // applies custom validations on after-validate event
        $validator->after(function ($validator) {

            // called class namespace
            $calledClass = get_called_class();

            // iterate over custom rules
            foreach ($this->customRules() as $property => $rules) {

                // iterate over validate methods list declared at called class 
                foreach ($rules as $rule) {

                    // checks whether the rule name set in custom rules 
                    // is correctly declared at called class as function
                    if (!method_exists($calledClass, $rule))
                        throw new \Exception(sprintf('Method %s does not exist at %s. Check your custom rules configuration', $rule, $calledClass));

                    // run custom validation rule
                    $errorMessage = call_user_func_array([$this, $rule], []);

                    // add error message
                    if (!empty($errorMessage))
                        $validator->errors()->add($property, $errorMessage);
                }
            }
        });
    }

    /**
     * Register validator and its custom rules to this class
     * 
     * @return void
     */
    private function _registerValidator()
    {
        // run validator with main rules
        $this->_initValidator();

        // register custom rules
        $this->_registerCustomRules();
    }

    /**
     * Update flag to inform that the method validate has been called
     *
     * @return void
     */
    private function _setDidValidate()
    {
        $this->didValidatorRun = true;
    }

    /**
     * Checks whether the validator has run by validate event
     * 
     * @return bool
     */
    private function _getDidValidatorRun() : bool
    {
        return $this->didValidatorRun;
    }

}

app/Models/Simulator.php
<?php

namespace App\Models;

use App\Models\Custom\BDSModel;
use Illuminate\Validation\Rule;

class Simulator extends BDSModel
{
    /**
     * Nome da tabela
     * 
     * @var string
     */
    protected $table = 'simulator';

    /**
     * Lista de propriedades da model que esta permitido o mass-assignment
     * 
     * @var array
     */
    protected $fillable = ['engine_id', 'frequency'];

    /**
     * Desabilitando timestamps para a tabela
     * 
     * @var boolean
     */
    public $timestamps = false;

    /**
     * Regras de validação
     * 
     * @return array
     */
    public function rules() : array 
    {
        return [
            'engine_id' => ['required', 'exists:engines,id', $this->getUniquenessRule()],
            'frequency' => 'required|integer|between:1,60'
        ];
    }

    /**
     * Relation has-one: Engine
     * 
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function engine() : \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo('\App\Models\Engine');
    }

    /**
     * Consulta todos os registros de maquinas e retorna uma collection paginada
     * 
     * @param  array  $filter 
     * @return \Illuminate\Pagination\LengthAwarePaginator
     */
    public static function fetchAll() : \Illuminate\Database\Eloquent\Collection
    {
        $query = Simulator::select('id', 'engine_id', 'frequency')
            ->with(['engine' => function($engineQuery) {
                $engineQuery
                    ->select('id', 'description', 'status_id', 'updated_at', 'deleted_at')
                    ->with(['status' => function($statusQuery) {
                        $statusQuery
                            ->select('id', 'description')
                            ->withTrashed();
                    }])
                    ->withTrashed();
            }]);

        return $query->get();
    }

    /**
     * Retorna a propriedade $frequency convertida para milisegundos
     * 
     * @return int
     */
    public function getFrequencyMsAttribute() : int
    {
        return intval($this->frequency ?? 0) * 1000;
    }

    /**
     * Getter para o atributo Engine::$description
     * 
     * @return string
     */
    public function getEngineDescriptionAttribute() : string
    {
        return $this->engine->description ?? '';
    }

    /**
     * Getter para a descrição do status da maquina (Engine)
     * 
     * @return string
     */
    public function getEngineStatusNameAttribute() : string
    {
        return $this->engine->status_name ?? '';
    }

    /**
     * Getter para a propriedade Engine::$updated_at
     * 
     * @return string
     */
    public function getEngineUpdatedAtAttribute() : string
    {
        return $this->engine->updated_at_br ?? '';
    }

    /**
     * Mutator para a propriedade status_id
     * Ao chamar o setter da propriedade faz o cast do valor 
     * do status selecionado para int
     * 
     * @param mixed $statusId
     */
    public function setStatusIdAttribute($statusId) : self
    {
        $this->attributes['status_id'] = intval($statusId);

        return $this;
    }

    /**
     * Accessor: Status::$description
     * 
     * @return string
     */
    public function getStatusNameAttribute() : string
    {
        return $this->status->description ?? '';
    }

    /**
     * Accessor para a propriedade created_at
     * 
     * @return string d/m/Y H:i:s
     */
    public function getCreatedAtBrAttribute() : string 
    {
        $datetime = new \DateTime($this->created_at);

        return $datetime->format('d/m/Y H:i:s');
    }

    /**
     * Accessor para a propriedade updated_at
     * 
     * @return string d/m/Y H:i:s
     */
    public function getUpdatedAtBrAttribute() : string 
    {
        $datetime = new \DateTime($this->updated_at);

        return $datetime->format('d/m/Y H:i:s');
    }

    /**
     * Regra custom para validacao de uniqueness
     *
     * @return Rule
     */
    private function getUniquenessRule() : \Illuminate\Validation\Rules\Unique
    {
        return $this->id == null
            ? Rule::unique($this->table)
            : Rule::unique($this->table)->ignore($this->id);
    }
}

app/Http/Controllers/Admin/SimulatorController.php
<?php 

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Symfony\Component\HttpFoundation\RedirectResponse;
use App\Models\Engine;
use App\Models\Simulator;
use App\Models\Status;

/**
 * Controller para o simulador de eventos
 */
class SimulatorController extends Controller 
{
    /**
     * Tela principal do simulador de eventos
     * 
     * @param Request $request
     * @return HTML simulator/index
     */
    public function index(Request $request)
    {
        $collection = Simulator::fetchAll();

        $successMessages = $request->session()->pull('simulator.success', []);
        $dangerMessages = $request->session()->pull('simulator.danger', []);

        return view('simulator.index', [
            'successMessages' => $successMessages,
            'dangerMessages'  => $dangerMessages,
            'collection'      => $collection
        ]);
    }

    /**
     * Form para criar novo registro de evento
     * 
     * @param \Illuminate\Http\Request $request
     * @return HTML simulator/create
     */
    public function create(Request $request)
    {
        $simulator = new Simulator;
        $engines = Engine::allByFilter();

        $response = $this->dispatchPersist($simulator, $request);

        if (null !== $response) {
            return $response;
        }

        return view('simulator.create', [
            'simulator' => $simulator,
            'engines'   => $engines
        ]);
    }

    /**
     * Form para editar um registro de evento
     * 
     * @param \Illuminate\Http\Request $request
     * @param integer $id
     * @return HTML simulator/update
     */
    public function update(Request $request, $id)
    {
        $simulator = Simulator::findOrFail($id);
        $engines = Engine::allByFilter();

        $response = $this->dispatchPersist($simulator, $request);

        if (null !== $response) {
            return $response;
        }

        return view('simulator.update', [
            'simulator' => $simulator,
            'engines'   => $engines
        ]);
    }

    /**
     * Action para remover um registro de simulator
     * 
     * @param \Illuminate\Http\Request $request
     * @param integer $id
     */
    public function delete(Request $request, $id)
    {
        $simulator = Simulator::findOrFail($id);

        try {
            $simulator->delete();
            $request->session()->push(
                'simulator.success', 'Dados removidos com sucesso'
            );
        } catch (\Exception $e) {
            $request->session()->push(
                'simulator.danger', sprintf(
                    'Houve um erro ao remover este registro. ERROR: %s', 
                    $e->getMessage()
                )
            );
        }

        return redirect('/admin/simulator');
    }

    /**
     * Atualiza o status de uma maquina registrada com um evento
     * para um status gerado aleatoriamente (de acordo com os status cadastrados e ATIVOS)
     *
     * Action disponivel apenas para requisicoes ajax
     * 
     * @param Request $request Objeto da request
     * @param int     $id      Id da maquina
     * @return []
     * @throws Exception se findOrFail falhar
     */
    public function updateEngine(Request $request, $id)
    {
        if ($request->ajax()) {
            $engine = Engine::findOrFail($id);
            $status = Status::inRandomOrder()->first();

            if ($status instanceof Status) {
                try {
                    $engine->status_id = $status->id;
                    $engine->save();

                    return [
                        'engine_status_name' => $status->description,
                        'engine_updated_at' => $engine->updated_at_br
                    ];
                } catch (\Exception $e) {
                    ;
                }
            }

            return [];
        }
    }

    /**
     * Popula a model Simulator com os dados da request e tenta executar o persist.
     * Em caso de sucesso retorna uma instance de RedirectResponse
     * 
     * @param Simulator &$simulator 
     * @param Request $request 
     * @return RedirectResponse|null
     */
    private function dispatchPersist(
        Simulator &$simulator, 
        Request $request
    ) {

        if ($request->isMethod('post')) {
            $simulator->fill($request->input('simulator', []));

            if ($simulator->validate()) {
                try {
                    $simulator->save();

                    $request->session()->push(
                        'simulator.success', 
                        'Dados salvos com sucesso!'
                    );
                } catch(\Exception $e) {
                    $request->session()->push(
                        'simulator.danger', sprintf('Houve um erro ao salvar as informações. ERROR: %s', $e->getMessage())
                    );
                }

                return redirect('/admin/simulator');
            }
        }

        return null;
    }
}

resources/views/simulator/_form.blade.php
<?php
/**
 * @var \App\Models\Simulator $simulator
 * @var Status[] $statuses
 */
?>

<div class="panel rounded shadow">
  
  @includeWhen($simulator->has_errors, 'components.dismissable-notice-panels.notice-warning', array(
    'messages' => $simulator->error_messages
  )) 

  <div class="panel-body">
    <div class="form-group">
      <label class="col-sm-3 control-label">M&aacute;quina:</label>
      <div class="col-sm-7">
        <select class="form-control input-md" name='simulator[engine_id]'>
          <option value="">Selecione uma op&ccedil;&atilde;o</option>
          @foreach ($engines as $engine)
            <option 
              value="{{ $engine->id }}"
              @php echo ($engine->id == $simulator->engine_id) ? ' selected="selected" ' : '' @endphp>
              {{ $engine->description }} 
            </option>
          @endforeach
        </select>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-3 control-label">Periodicidade (Segundos):</label>
      <div class="col-sm-7">
        <input 
          type="text" 
          name='simulator[frequency]' 
          class="form-control input-md js-number_only" 
          placeholder="Frequencia em seg. para o evento atribuido a máquina ocorrer" 
          value="{{ $simulator->frequency }}" />
      </div>
    </div>
  </div>
</div>

<div class="form-footer">
  <div class="col-sm-offset-3">
    <button type="submit" class="btn btn-success"><i class="fa fa-floppy-o"></i> Salvar</button>
    <a href="/admin/simulator" class="btn btn-primary"><i class="fa fa-reply"></i> Voltar</a>
  </div>
</div>


<script>
  document.addEventListener('DOMContentLoaded', function() {
    $('.js-number_only').on('keypress keyup', function() {
      this.value = this.value.replace(/[^\d]+/g, "");
    })
  });
</script>

resources/views/simulator/create.blade.php
<?php
/**
 * @var \App\Models\Engine[] $engines
 */
?>

<!-- default layout theme -->
@extends('layouts.admin')

<!-- header and breadcrumbs -->
@include('simulator.page-header')

@section('content')
<div class="row">
  <div class="col-md-12">
    <div class="panel rounded shadow no-overflow">
      <div class="panel-body no-padding">
        <form 
          class="form-horizontal form-bordered" 
          role="form" 
          method="post" 
          action="/admin/simulator/create">
          {{ csrf_field() }}

          @include('simulator._form')
        </form>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/simulator/index.blade.php
<?php
/**
 * @var \Illuminate\Pagination\LengthAwarePaginator $collection (Engine)
 * @var array $successMessages
 * @var array $dangerMessages
 * @var array $filter
 * @var Status[] $statuses
 */ 
?>

<!-- default layout theme -->
@extends('layouts.admin')

<!-- header and breadcrumbs -->
@include('simulator.page-header')

@section('content')
  <!-- success messages component -->
  @includeWhen($successMessages, 'components.dismissable-notice-panels.notice-info', array(
    'messages' => $successMessages
  ))

  <!-- danger messages component -->
  @includeWhen($dangerMessages, 'components.dismissable-notice-panels.notice-danger', array(
    'messages' => $dangerMessages
  )) 

  @if (count($collection))
    @foreach ($collection as $row)
      <div 
        class="col-lg-3 col-md-3 col-sm-6 col-xs-6 js-engine_container" 
        data-id="{{ $row->engine_id }}"
        data-frequency_ms="{{ $row->frequency_ms }}">
        <div class="panel rounded shadow">
          <div class="panel-body">
            <ul class="inner-all list-unstyled">
              <li class="text-center">
                <h4 class="text-capitalize">{{ $row->engine_description }}</h4>
              </li>
              <li>
                <ul class="list-group no-margin br-3">
                  <li class="list-group-item">
                    <i class="fa fa-tag mr-5"></i><span class="js-engine_status_name">{{ $row->engine_status_name }}</span>
                  </li>
                  <li class="list-group-item">
                    <i class="fa fa-refresh mr-5"></i>Atualiza&ccedil;&atilde;o a cada {{ $row->frequency }} segundos
                  </li>
                  <li class="list-group-item">
                    <i class="fa fa-globe mr-5"></i>&Uacute;ltima atualiza&ccedil;&atilde;o: <span class="js-engine_updated_at">{{ $row->engine_updated_at }}</span>
                  </li>
                </ul>
              </li>
              <li class="text-center">
                <a href="/admin/simulator/update/{{ $row->id }}" class="btn btn-primary btn-xs" title="Editar Registro"><i class="fa fa-pencil"></i></a>
                <a href="/admin/simulator/delete/{{ $row->id }}" class="btn btn-danger btn-xs js-confirm-to-remove" title="Remover Registro"><i class="fa fa-trash-o"></i></a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    @endforeach
  @else 
    <b>N&atilde;o h&aacute; eventos de status configurado para as m&aacute;quinas<b>
  @endif
@endsection

@push('javascript-modules')
  <script src="/js/modules/simulator/index.js"></script>
@endpush

resources/views/simulator/page-header.blade.php
@section('page-header')
<h2>
  <a href="/admin/simulator/create"><i class="fa fa-file-o"></i></a>
  Simulador de Eventos<span>Configura&ccedil;&atilde;o de visualiza&ccedil;&atilde;o dos eventos atribu&iacute;dos as m&aacute;quinas</span>
</h2>

<div class="breadcrumb-wrapper hidden-xs">
  <span class="label">Voc&ecirc; est&aacute; aqui:</span>
  <ol class="breadcrumb">
    <li class="active">Simulador de Eventos</li>
  </ol>
</div>
@endsection

resources/views/simulator/update.blade.php
<?php
/**
 * @var \App\Models\Engine[] $engines
 */
?>

<!-- default layout theme -->
@extends('layouts.admin')

<!-- header and breadcrumbs -->
@include('simulator.page-header')

@section('content')
<div class="row">
  <div class="col-md-12">
    <div class="panel rounded shadow no-overflow">
      <div class="panel-body no-padding">
        <form 
          class="form-horizontal form-bordered" 
          role="form" 
          method="post" 
          action="/admin/simulator/update/{{ $simulator->id }}">
          {{ csrf_field() }}

          @include('simulator._form')
        </form>
      </div>
    </div>
  </div>
</div>
@endsection