routes/web.php
<?php
/*
 * Rotas para a área restrita
 */
Route::namespace('Admin')->group(function() {
    /*
     * As rotas definidas abaixo pertencem a area restrita
     * e são executadas atravez do middleware de autenticação
     * Se o usuário não estiver autenticado na ferramenta, ele será redirecoinado para a tela de login 
     */
    Route::group(['middleware' => 'auth'], function() {

        /*
         * Rotas para o modulo de Status
         */
        Route::get('/admin/statuses', 'StatusController@index');
        Route::match(['get', 'post'], '/admin/status/create', 'StatusController@create');
        Route::match(['get', 'post'], '/admin/status/update/{id}', 'StatusController@update');
        Route::get('/admin/status/delete/{id}', 'StatusController@delete');
        Route::get('/admin/status/{id}', 'StatusController@show');

        /*
         * Rotas para o modulo de maquinas 
         */
        Route::get('/admin/engines', 'EngineController@index');
        Route::match(['get', 'post'], '/admin/engine/create', 'EngineController@create');
        Route::match(['get', 'post'], '/admin/engine/update/{id}', 'EngineController@update');
        Route::get('/admin/engine/delete/{id}', 'EngineController@delete');
        Route::get('/admin/engine/{id}', 'EngineController@show');

        /*
         * Rotas para o simulador de eventos 
         */
        Route::get('/admin/simulator', 'SimulatorController@index');
        Route::match(['get', 'post'], '/admin/simulator/create', 'SimulatorController@create');
        Route::match(['get', 'post'], '/admin/simulator/update/{id}', 'SimulatorController@update');
        Route::get('/admin/simulator/delete/{id}', 'SimulatorController@delete');
        Route::get('/admin/simulator/update-engine/{id}', 'SimulatorController@updateEngine');
    });
});

/*
 * Rotas de autenticação
 */
Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/login', 'Auth\LoginController@login');
Route::get('/logout', 'Auth\LoginController@logout')->name('logout');

app/Models/Custom/BDSModel.php
<?php

namespace App\Models\Custom;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Validator as FacadeValidator;
use Illuminate\Validation\Validator;

/**
 * This class implements validations methods used by it called class
 *
 * The called class must implement a public customRules method, 
 * which must return a key pair array used by Illuminate\Support\Facades\Validator
 * Check Laravel documentation page for facade validator
 *
 * To create custom validation rules, your model must contain a method customRules,
 * which will return a key pair array values. 
 * Its key should be the property to be validated.
 * Its value should be an array, with method names inside its class
 *
 * Sample return for customRules method: 
 * 
 * [
 *   'field1' => ['validationMethod1', 'validationMethod2'],
 *   'field2' => ['validationMethod2']
 * ]
 * 
 * - In this sample, 'validationMethod1' and 'validationMethod2' must be declared on its called class 
 * and should return an string with the error, or an empty string
 *
 * @author Bruno Vieira <vrunobieira@gmail.com>
 */
abstract class BDSModel extends Model
{

    /**
     * Validator object
     * 
     * @var \Illuminate\Validation\Validator
     */
    private $validator = null;

    /**
     * Checks whether the validator was called previously by the model
     * 
     * @var boolean
     */
    private $didValidatorRun = false;

    /**
     * Call parent constructor an dispatch validator events
     * 
     * @param array $attributes 
     */
    public function __construct(array $attributes = [])
    {
        // run parent constructor
        parent::__construct($attributes);

        // register the validator within the class
        $this->_registerValidator();
    }

    /**
     * Accessor for getErrorMessages()
     * 
     * @return array
     */
    public function getErrorMessagesAttribute() : array
    {
        return $this->getErrorMessages();
    }

    /**
     * Accessor for hasErrors()
     * 
     * @return bool
     */
    public function getHasErrorsAttribute() : bool
    {
        return $this->hasErrors();
    }

    /**
     * Run model validations
     *
     * @return bool
     */
    public function validate() : bool
    {
        // register the validator within the class
        $this->_registerValidator();

        // change flag to inform the validator has run by public call
        $this->_setDidValidate();

        // returns true if does not contain errors
        return !$this->hasErrors();
    }

    /**
     * Checks whether the validation has run and the model has errors
     * 
     * @var boolean
     */
    public function hasErrors() : bool
    {
        return $this->_getDidValidatorRun()
            ? $this->_getValidator()->fails()
            : false;
    }

    /**
     * Retrieves error messages list
     * 
     * @return array
     */
    public function getErrorMessages() : array
    {
        return $this->hasErrors()
            ? $this->_getValidator()->errors()->all()
            : [];
    }

    /**
     * Setter for BDSModel::$validator
     * 
     * @param Illuminate\Validation\Validator $validator 
     * @return void
     */
    private function _setValidator(Validator $validator)
    {
        $this->validator = $validator;
    }

    /**
     * Getter for BDSModel::$validator
     * 
     * @return Illuminate\Validation\Validator
     */
    private function _getValidator() : Validator
    {
        return $this->validator;
    }

    /**
     * Start new validator and binds it to this class
     * 
     * @return void
     */
    private function _initValidator()
    {
        $validator = FacadeValidator::make($this->getAttributes(), $this->rules());

        $this->_setValidator($validator);
    }

    /**
     * Getter for $validator
     * 
     * @return Illuminate\Validation\Validator
     */
    protected function getValidator() : Validator
    {
        return $this->validator;
    }

    /**
     * Run additional validations registered by called class
     * 
     * @return void
     */
    private function _registerCustomRules()
    {
        // checks whether the customRules method is declared on called class
        // otherwise bypass register event
        if (!method_exists(get_called_class(), 'customRules')) 
            return;

        // get validator object
        $validator = $this->_getValidator();

        // applies custom validations on after-validate event
        $validator->after(function ($validator) {

            // called class namespace
            $calledClass = get_called_class();

            // iterate over custom rules
            foreach ($this->customRules() as $property => $rules) {

                // iterate over validate methods list declared at called class 
                foreach ($rules as $rule) {

                    // checks whether the rule name set in custom rules 
                    // is correctly declared at called class as function
                    if (!method_exists($calledClass, $rule))
                        throw new \Exception(sprintf('Method %s does not exist at %s. Check your custom rules configuration', $rule, $calledClass));

                    // run custom validation rule
                    $errorMessage = call_user_func_array([$this, $rule], []);

                    // add error message
                    if (!empty($errorMessage))
                        $validator->errors()->add($property, $errorMessage);
                }
            }
        });
    }

    /**
     * Register validator and its custom rules to this class
     * 
     * @return void
     */
    private function _registerValidator()
    {
        // run validator with main rules
        $this->_initValidator();

        // register custom rules
        $this->_registerCustomRules();
    }

    /**
     * Update flag to inform that the method validate has been called
     *
     * @return void
     */
    private function _setDidValidate()
    {
        $this->didValidatorRun = true;
    }

    /**
     * Checks whether the validator has run by validate event
     * 
     * @return bool
     */
    private function _getDidValidatorRun() : bool
    {
        return $this->didValidatorRun;
    }

}

app/Models/Engine.php
<?php

namespace App\Models;

use App\Models\Custom\BDSModel;
use Illuminate\Validation\Rule;
use Illuminate\Database\Eloquent\SoftDeletes;

class Engine extends BDSModel
{
    /**
     * Trait para habilitar soft-delete
     */
    use SoftDeletes;

    /**
     * Lista de propriedades da model que esta permitido o mass-assignment
     * 
     * @var array
     */
    protected $fillable = ['description', 'status_id'];

    /**
     * Regras de validação
     * 
     * @return array
     */
    public function rules() : array 
    {
        return [
            'description' => 'required|string|max:255',
            'status_id'   => 'required|exists:statuses,id|integer'
        ];
    }

    /**
     * Relation belongs-to: Status
     * 
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function status() : \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo('\App\Models\Status');
    }

    /**
     * Consulta todos os registros de maquinas e retorna uma collection paginada
     * 
     * @param  array  $filter 
     * @return \Illuminate\Pagination\LengthAwarePaginator
     */
    public static function allByFilter(array $filter = []) : \Illuminate\Pagination\LengthAwarePaginator
    {
        $query = Engine::select('id', 'description', 'status_id', 'created_at', 'updated_at')
            ->with(['status' => function($query) {
                $query->select('id', 'description')->withTrashed();
            }]);

        if (isset($filter['status']) && intval($filter['status']) > 0) {
            $query->where('status_id', $filter['status']);
        }

        if (isset($filter['search']) && !empty($filter['search'])) {
            $query->where('description', 'like', '%' . $filter['search'] . '%');
        }

        return $query->paginate(10);
    }

    /**
     * Mutator para a propriedade status_id
     * Ao chamar o setter da propriedade faz o cast do valor 
     * do status selecionado para int
     * 
     * @param mixed $statusId
     */
    public function setStatusIdAttribute($statusId) : self
    {
        $this->attributes['status_id'] = intval($statusId);

        return $this;
    }

    /**
     * Accessor: Status::$description
     * 
     * @return string
     */
    public function getStatusNameAttribute() : string
    {
        return $this->status->description ?? '';
    }

    /**
     * Accessor para a propriedade created_at
     * 
     * @return string d/m/Y H:i:s
     */
    public function getCreatedAtBrAttribute() : string 
    {
        $datetime = new \DateTime($this->created_at);

        return $datetime->format('d/m/Y H:i:s');
    }

    /**
     * Accessor para a propriedade updated_at
     * 
     * @return string d/m/Y H:i:s
     */
    public function getUpdatedAtBrAttribute() : string 
    {
        $datetime = new \DateTime($this->updated_at);

        return $datetime->format('d/m/Y H:i:s');
    }
}

app/Http/Controllers/Admin/EngineController.php
<?php 

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Symfony\Component\HttpFoundation\RedirectResponse;
use App\Models\Engine;
use App\Models\Status;

/**
 * Controller para o modulo de maquinas
 */
class EngineController extends Controller 
{
    /**
     * Index para o modulo de maquinas
     * 
     * @param Request $request
     * @return HTML engines/index
     */
    public function index(Request $request)
    {
        $filter = $this->getFilterParams($request);
        $collection = Engine::allByFilter($filter);
        $statuses = Status::allByFilter();

        $successMessages = $request->session()->pull('engine.success', []);
        $dangerMessages = $request->session()->pull('engine.danger', []);

        return view('engines.index', [
            'successMessages' => $successMessages,
            'dangerMessages'  => $dangerMessages,
            'filter'          => $filter,
            'collection'      => $collection,
            'statuses'        => $statuses
        ]);
    }

    /**
     * Form para criar novo registro de maquina
     * 
     * @param \Illuminate\Http\Request $request
     * @return HTML engines/create
     */
    public function create(Request $request)
    {
        $engine = new Engine;
        $statuses = Status::allByFilter();

        $response = $this->dispatchPersist($engine, $request);

        if (null !== $response) {
            return $response;
        }

        return view('engines.create', [
            'engine'    => $engine,
            'statuses'  => $statuses
        ]);
    }

    /**
     * Form para editar um registro de maquina
     * 
     * @param \Illuminate\Http\Request $request
     * @param integer $id
     * @return HTML engines/update
     */
    public function update(Request $request, $id)
    {
        $engine = Engine::findOrFail($id);
        $statuses = Status::allByFilter();

        $response = $this->dispatchPersist($engine, $request);

        if (null !== $response) {
            return $response;
        }

        return view('engines.update', [
            'engine'    => $engine,
            'statuses'  => $statuses
        ]);
    }

    /**
     * Action para remover um registro de maquina
     * 
     * @param \Illuminate\Http\Request $request
     * @param integer $id
     */
    public function delete(Request $request, $id)
    {
        $engine = Engine::findOrFail($id);

        try {
            $engine->delete();
            $request->session()->push(
                'engine.success', 'Dados removidos com sucesso'
            );
        } catch (\Exception $e) {
            $request->session()->push(
                'engine.danger', sprintf(
                    'Houve um erro ao remover este registro. ERROR: %s', 
                    $e->getMessage()
                )
            );
        }

        return redirect('/admin/engines');
    }

    /**
     * Tela para exibir o registro de maquina
     * 
     * @param integer $id
     * @return HTML engines/show
     */
    public function show($id)
    {
        return view('engines.show', [
            'engine' => Engine::findOrFail($id)
        ]);
    }

    /**
     * Popula a model Engine com os dados da request e tenta executar o persist.
     * Em caso de sucesso retorna uma instance de RedirectResponse
     * 
     * @param Engine  &$engine 
     * @param Request $request 
     * @return RedirectResponse|null
     */
    private function dispatchPersist(
        Engine &$engine, 
        Request $request
    ) {

        if ($request->isMethod('post')) {
            $requestData = $request->input('engine', []);

            $engine
                ->fill($requestData)
                ->setStatusIdAttribute($requestData['status_id'] ?? null);

            if ($engine->validate()) {
                try {
                    $engine->save();

                    $request->session()->push(
                        'engine.success', 
                        'Dados salvos com sucesso!'
                    );
                } catch(\Exception $e) {
                    $request->session()->push(
                        'engine.danger', sprintf('Houve um erro ao salvar as informações. ERROR: %s', $e->getMessage())
                    );
                }

                return redirect('/admin/engines');
            }
        }

        return null;
    }

    /**
     * Retorna os dados dos filtros de pesquisa
     * 
     * @param  Request $request
     * @return array
     *             - status: int
     *             - search: string
     */
    private function getFilterParams(Request $request) : array
    {
        return [
            'status' => intval($request->input('filter.status', 0)),
            'search' => $request->input('filter.search', '')
        ];
    }
}

resources/views/engines/_form.blade.php
<?php
/**
 * @var \App\Models\Engine $engine
 * @var Status[] $statuses
 */
?>

<div class="panel rounded shadow">
  
  @includeWhen($engine->has_errors, 'components.dismissable-notice-panels.notice-warning', array(
    'messages' => $engine->error_messages
  )) 

  <div class="panel-body">
    <div class="form-group">
      <label class="col-sm-3 control-label">Descri&ccedil;&atilde;o:</label>
      <div class="col-sm-7">
        <input 
          type="text" 
          name='engine[description]' 
          class="form-control input-md" 
          placeholder="Nome da máquina" 
          value="{{ $engine->description }}" />
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-3 control-label">Status:</label>
      <div class="col-sm-7">
        <select class="form-control input-md" name='engine[status_id]'>
          <option value="">Selecione uma op&ccedil;&atilde;o</option>
          @foreach ($statuses as $status)
            <option 
              value="{{ $status->id }}"
              @php echo ($status->id == $engine->status_id) ? ' selected="selected" ' : '' @endphp>
              {{ $status->description }} 
            </option>
          @endforeach
        </select>
      </div>
    </div>
  </div>
</div>

<div class="form-footer">
  <div class="col-sm-offset-3">
    <button type="submit" class="btn btn-success"><i class="fa fa-floppy-o"></i> Salvar</button>
    <a href="/admin/engines" class="btn btn-primary"><i class="fa fa-reply"></i> Voltar</a>
  </div>
</div>

resources/views/engines/create.blade.php
<?php
/**
 * @var \App\Models\Engine $engine
 * @var Status[] $statuses
 */
?>

<!-- default layout theme -->
@extends('layouts.admin')

<!-- header and breadcrumbs -->
@include('engines.page-header')

@section('content')
<div class="row">
  <div class="col-md-12">
    <div class="panel rounded shadow no-overflow">
      <div class="panel-body no-padding">
        <form 
          class="form-horizontal form-bordered" 
          role="form" 
          method="post" 
          action="/admin/engine/create">
          {{ csrf_field() }}

          @include('engines._form')
        </form>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/engines/index.blade.php
<?php
/**
 * @var \Illuminate\Pagination\LengthAwarePaginator $collection (Engine)
 * @var array $successMessages
 * @var array $dangerMessages
 * @var array $filter
 * @var Status[] $statuses
 */ 
?>

<!-- default layout theme -->
@extends('layouts.admin')

<!-- top search bar -->
@include('engines.search', array(
  'filter'   => $filter,
  'statuses' => $statuses
)) 

<!-- header and breadcrumbs -->
@include('engines.page-header')

@section('content')
  <!-- success messages component -->
  @includeWhen($successMessages, 'components.dismissable-notice-panels.notice-info', array(
    'messages' => $successMessages
  ))

  <!-- danger messages component -->
  @includeWhen($dangerMessages, 'components.dismissable-notice-panels.notice-danger', array(
    'messages' => $dangerMessages
  )) 

  <div class="row">
    <div class="col-md-12">
      <div class="panel shadow">
        <div class="panel-body">
          <div class="table-responsive" style="margin-top: -1px;">
            <table class="table table-striped table-success">
              <thead>
              <tr>
                <th class="text-center border-right" style="width: 1%;">#</th>
                <th>Descri&ccedil;&atilde;o</th>
                <th>Status</th>
                <th>Criado em</th>
                <th>Atualizado em</th>
                <th class="text-center" style="width: 12%;"></th>
              </tr>
              </thead>
              <tbody>
              @if (count($collection))
                @foreach ($collection as $row)
                <tr>
                  <td class="text-center border-right">{{ $row->id }}</td>
                  <td><span>{{ $row->description }}</span></td>
                  <td>{{ $row->status_name }}</td>
                  <td>{{ $row->created_at_br }}</td>
                  <td>{{ $row->updated_at_br }}</td>
                  <td class="text-center">
                    <a href="/admin/engine/{{ $row->id }}" class="btn btn-success btn-xs" title="Exibir Registro"><i class="fa fa-eye"></i></a>
                    <a href="/admin/engine/update/{{ $row->id }}" class="btn btn-primary btn-xs" title="Editar Registro"><i class="fa fa-pencil"></i></a>
                    <a href="/admin/engine/delete/{{ $row->id }}" class="btn btn-danger btn-xs js-confirm-to-remove" title="Remover Registro"><i class="fa fa-trash-o"></i></a>
                  </td>
                </tr>
                @endforeach
              @else 
                <tr>
                  <td colspan="5"><b>Nenhum registro encontrado<b></td>
                </tr>
              @endif
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- paginator -->
  {{ $collection->appends(['filter' => $filter])->links() }}
@endsection

resources/views/engines/page-header.blade.php
@section('page-header')

<h2>
  <a href="/admin/engine/create"><i class="fa fa-file-o"></i></a>
  M&aacute;quinas<span>Cadastro e gerenciamento de m&aacute;quinas</span>
</h2>

<div class="breadcrumb-wrapper hidden-xs">
  <span class="label">Voc&ecirc; est&aacute; aqui:</span>
  <ol class="breadcrumb">
    <li>
      <i class="fa fa-home"></i>
      <a href="javascript: void(0);">Simulador de Eventos</a>
      <i class="fa fa-angle-right"></i>
    </li>
    <li class="active">M&aacute;quinas</li>
  </ol>
</div>
@endsection

resources/views/engines/search.blade.php
<?php
/**
 * @var array $filter
 * @var Status[] $statuses
 */
?>
@section('search-form')

<li class="navbar-search">
  <a href="#" class="trigger-search">
    <i class="fa fa-search"></i>
  </a>
  <form class="navbar-form" action="/admin/engines">
    <div class="form-group has-feedback">
      <select name="filter[status]" class="form-control">
        <option value="">Status</option>
        @foreach ($statuses as $status)
          <option 
            value="{{ $status->id }}" 
            @php echo ($status->id == $filter['status']) ? ' selected="selected" ' : '' @endphp> 
            {{ $status->description }} 
          </option>  
        @endforeach
      </select>
    </div>
    <div class="form-group has-feedback">
      <input type="text" name="filter[search]" value="{{ $filter['search'] }}" class="form-control rounded" placeholder="Pesquisa por descri&ccedil;&atilde;o">
      <button type="submit" class="btn btn-theme fa fa-search form-control-feedback rounded"></button>
    </div>
  </form>
</li>
@endsection

resources/views/engines/show.blade.php
<?php
/**
 * @var \App\Models\Engine $engine
 */
?>

@extends('layouts.admin')

@include('engines.page-header')

@section('content')
<div class="row">
  <div class="col-md-12">
    <div class="panel rounded shadow">
      <div class="panel-body">
        <div class="table-responsive" style="margin-top: -1px;">
          <table class="table table-striped table-success">
            <tbody>
              <tr>
                <th>Id</th>
                <td>{{ $engine->id }}</td>
              </tr>
              <tr>
                <th width="18%">Descri&ccedil;&atilde;o</th>
                <td>{{ $engine->description }}</td>
              </tr>
              <tr>
                <th>Status</th>
                <td>{{ $engine->status_name }}</td>
              </tr>
              <tr>
                <th>Criado em</th>
                <td>{{ $engine->created_at_br }}</td>
              </tr>
              <tr>
                <th>Atualizado em</th>
                <td>{{ $engine->updated_at_br }}</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

      <div class="form-footer">
        <div>
          <a href="/admin/engines" class="btn btn-primary"><i class="fa fa-reply"></i> Voltar</a>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/engines/update.blade.php
<?php
/**
 * @var \App\Models\Engine $engine
 * @var Status[] $statuses
 */
?>

<!-- default layout theme -->
@extends('layouts.admin')

<!-- header and breadcrumbs -->
@include('engines.page-header')

@section('content')
<div class="row">
  <div class="col-md-12">
    <div class="panel rounded shadow no-overflow">
      <div class="panel-body no-padding">
        <form class="form-horizontal form-bordered" role="form" method="post" action="/admin/engine/update/{{ $engine->id }}">
          {{ csrf_field() }}

          @include('engines._form')
        </form>
      </div>
    </div>
  </div>
</div>
@endsection